name = "my_portfolio_website"
account_id = "90319eafaf3502b6960e2275ffcf3dff"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

compatibility_date = "2024-07-11"
workers_dev = true